In [1]:
%%capture
!pip install unsloth trl transformers datasets wandb

In [2]:
from datasets import load_dataset
import json, os

# Load Nebius OpenHands trajectories
ds = load_dataset("nebius/SWE-rebench-openhands-trajectories", split="train")
print(ds)
print(ds[0].keys())

README.md: 0.00B [00:00, ?B/s]

trajectories.parquet:   0%|          | 0.00/2.08G [00:00<?, ?B/s]

Generating train split:   0%|          | 0/67074 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/17 [00:00<?, ?it/s]

Dataset({
    features: ['trajectory_id', 'instance_id', 'repo', 'trajectory', 'tools', 'model_patch', 'exit_status', 'resolved', 'gen_tests_correct', 'pred_passes_gen_tests'],
    num_rows: 67074
})
dict_keys(['trajectory_id', 'instance_id', 'repo', 'trajectory', 'tools', 'model_patch', 'exit_status', 'resolved', 'gen_tests_correct', 'pred_passes_gen_tests'])

In [3]:
import json

# one resolved and one unresolved example
resolved = next(x for x in ds if x["resolved"] == True)
unresolved = next(x for x in ds if x["resolved"] == False)

print("Resolved Example:")
print("instance_id:", resolved["instance_id"])
print("exit_status:", resolved["exit_status"])
print("trajectory type:", type(resolved["trajectory"]))
print("trajectory keys (if dict):", resolved["trajectory"].keys() if isinstance(resolved["trajectory"], dict) else "not a dict")
print()
print("Unresolved Example:")
print("instance_id:", unresolved["instance_id"])
print("exit_status:", unresolved["exit_status"])
print()

# first 2 msgs of the resolved trajectory
traj = resolved["trajectory"]
if isinstance(traj, dict):
    messages = traj.get("messages", traj.get("history", []))
elif isinstance(traj, list):
    messages = traj
print("First message:", json.dumps(messages[0], indent=2)[:500])

Resolved Example:
instance_id: tianocore__edk2-pytool-library-372
exit_status: submit
trajectory type: <class 'list'>
trajectory keys (if dict): not a dict

Unresolved Example:
instance_id: PlasmaFAIR__sdf-xarray-24
exit_status: submit

First message: {
  "content": "You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.\n\n<ROLE>\nYour primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize quality over speed.\n* If the user asks a question, like \"why is X happening\", don't try to fix the problem. Just give an answer to the question.\n</ROLE>\n\n<EFFICIENCY>\n* Each action you take is some

### Getting full message structure

In [4]:
traj = resolved["trajectory"]
print(f"Total messages: {len(traj)}")
for i, msg in enumerate(traj[:5]):
    print(f"\n--- Message {i} ---")
    print("Keys:", msg.keys())
    print("Role:", msg.get("role", "N/A"))
    content = str(msg.get("content", ""))[:200]
    print("Content preview:", content)

Total messages: 91

--- Message 0 ---
Keys: dict_keys(['content', 'name', 'role', 'tool_call_id', 'tool_calls'])
Role: system
Content preview: You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving techni

--- Message 1 ---
Keys: dict_keys(['content', 'name', 'role', 'tool_call_id', 'tool_calls'])
Role: user
Content preview: <uploaded_files>
/workspace/tianocore__edk2-pytool-library__0.15
</uploaded_files>

I've uploaded a python code repository in the directory tianocore__edk2-pytool-library__0.15. Consider the following

--- Message 2 ---
Keys: dict_keys(['content', 'name', 'role', 'tool_call_id', 'tool_calls'])
Role: assistant
Content preview: I'll help you implement the necessary changes to fix the issue with `GetEdk2RelativePathFromAbsolutePath()` silently returning non-POSIX paths. Let me start by following the phases you outlined.

## P

--- Message 3 ---
Keys: dict_keys(['content', 'name', 'role', 'tool_call_id', 'tool_calls'])
Role: tool
Content preview: Your thought has been logged.

--- Message 4 ---
Keys: dict_keys(['content', 'name', 'role', 'tool_call_id', 'tool_calls'])
Role: assistant
Content preview: ## Phase 2. RUNNING: Setting up and Running Tests

### Num. valid dpo pairs we can make

In [5]:
from collections import defaultdict

# group trajectories by instance_id
instance_groups = defaultdict(lambda: {"resolved": [], "unresolved": []})

for ex in ds:
    iid = ex["instance_id"]
    if ex["resolved"]:
        instance_groups[iid]["resolved"].append(ex)
    else:
        instance_groups[iid]["unresolved"].append(ex)

# count instances with both resolved and unresolved runs
valid_pairs = {k: v for k, v in instance_groups.items()
               if len(v["resolved"]) > 0 and len(v["unresolved"]) > 0}

print(f"Total unique instances: {len(instance_groups)}")
print(f"Instances with valid DPO pairs: {len(valid_pairs)}")
print(f"Potential DPO pairs: {sum(len(v['resolved']) * len(v['unresolved']) for v in valid_pairs.values())}")

Total unique instances: 6306
Instances with valid DPO pairs: 1741
Potential DPO pairs: 38576

### Constructing DPO Pairs

In [6]:
import json
import os
from collections import defaultdict

def extract_text_content(msg):
    content = msg.get("content", "")
    if isinstance(content, list):
        # some messages have content as a list of blocks
        return " ".join(
            block.get("text", "") if isinstance(block, dict) else str(block)
            for block in content
        )
    return str(content) if content else ""

def trajectory_to_text(messages):
    """Convert a trajectory's messages into a single training string."""
    text = ""
    for msg in messages:
        role = msg.get("role", "")
        content = extract_text_content(msg)
        if not content.strip():
            continue
        if role == "system":
            text += f"<start_of_turn>system\n{content}<end_of_turn>\n"
        elif role == "user":
            text += f"<start_of_turn>user\n{content}<end_of_turn>\n"
        elif role == "assistant":
            text += f"<start_of_turn>model\n{content}<end_of_turn>\n"
        elif role == "tool":
            text += f"<start_of_turn>tool\n{content}<end_of_turn>\n"
    return text

def count_llm_calls(messages):
    """Count how many assistant turns exist; proxy for frontier model invocations."""
    return sum(1 for m in messages if m.get("role") == "assistant")

# group by instance_id
instance_groups = defaultdict(lambda: {"resolved": [], "unresolved": []})
for ex in ds:
    iid = ex["instance_id"]
    if ex["resolved"]:
        instance_groups[iid]["resolved"].append(ex)
    else:
        instance_groups[iid]["unresolved"].append(ex)

# Build DPO pairs
dpo_pairs = []
for iid, group in instance_groups.items():
    if not group["resolved"] or not group["unresolved"]:
        continue

    # pick resolved trajectory w least LLM calls (most efficient)
    chosen_ex = min(group["resolved"],
                    key=lambda x: count_llm_calls(x["trajectory"]))

    # pick unresolved trajectory w most LLM calls (most wasteful)
    rejected_ex = max(group["unresolved"],
                      key=lambda x: count_llm_calls(x["trajectory"]))

    chosen_text = trajectory_to_text(chosen_ex["trajectory"])
    rejected_text = trajectory_to_text(rejected_ex["trajectory"])

    # skip if either empty or identical
    if not chosen_text.strip() or not rejected_text.strip():
        continue
    if chosen_text == rejected_text:
        continue

    dpo_pairs.append({
        "instance_id": iid,
        "prompt": f"Resolve the following GitHub issue efficiently:\n{extract_text_content(chosen_ex['trajectory'][1])}",
        "chosen": chosen_text,
        "rejected": rejected_text,
        "chosen_llm_calls": count_llm_calls(chosen_ex["trajectory"]),
        "rejected_llm_calls": count_llm_calls(rejected_ex["trajectory"]),
    })

print(f"Built {len(dpo_pairs)} DPO pairs")
print(f"\nSample pair:")
print(f"  instance_id: {dpo_pairs[0]['instance_id']}")
print(f"  chosen LLM calls: {dpo_pairs[0]['chosen_llm_calls']}")
print(f"  rejected LLM calls: {dpo_pairs[0]['rejected_llm_calls']}")

# save
os.makedirs("data/processed", exist_ok=True)
with open("data/processed/dpo_pairs.jsonl", "w") as f:
    for pair in dpo_pairs:
        f.write(json.dumps(pair) + "\n")

print(f"\nSaved to data/processed/dpo_pairs.jsonl")

Built 1741 DPO pairs

Sample pair:
  instance_id: PyPSA__linopy-79
  chosen LLM calls: 68
  rejected LLM calls: 100

Saved to data/processed/dpo_pairs.jsonl

### Checking distribution of all pairs b4 training

In [8]:
import numpy as np

chosen_calls = [p["chosen_llm_calls"] for p in dpo_pairs]
rejected_calls = [p["rejected_llm_calls"] for p in dpo_pairs]
differences = [r - c for c, r in zip(chosen_calls, rejected_calls)]

print(f"Chosen (efficient) trajectories")
print(f"  Mean LLM calls: {np.mean(chosen_calls):.1f}")
print(f"  Median LLM calls: {np.median(chosen_calls):.1f}")
print(f"  Min/Max: {min(chosen_calls)} / {max(chosen_calls)}")

print(f"\nRejected (wasteful) trajectories")
print(f"  Mean LLM calls: {np.mean(rejected_calls):.1f}")
print(f"  Median LLM calls: {np.median(rejected_calls):.1f}")
print(f"  Min/Max: {min(rejected_calls)} / {max(rejected_calls)}")

print(f"\nWaste Gap (rejected - chosen)")
print(f"  Mean waste: {np.mean(differences):.1f} extra LLM calls per task")
print(f"  Median waste: {np.median(differences):.1f}")
print(f"  Pairs where rejected used MORE calls: {sum(1 for d in differences if d > 0)} / {len(differences)}")
print(f"  Pairs where rejected used FEWER calls: {sum(1 for d in differences if d < 0)} / {len(differences)}")

Chosen (efficient) trajectories
  Mean LLM calls: 58.0
  Median LLM calls: 55.0
  Min/Max: 24 / 100

Rejected (wasteful) trajectories
  Mean LLM calls: 79.8
  Median LLM calls: 83.0
  Min/Max: 21 / 100

Waste Gap (rejected - chosen)
  Mean waste: 21.9 extra LLM calls per task
  Median waste: 21.0
  Pairs where rejected used MORE calls: 1569 / 1741
  Pairs where rejected used FEWER calls: 100 / 1741

### Running DPO

In [14]:
import unsloth
from unsloth import FastLanguageModel
from trl import DPOTrainer, DPOConfig
from datasets import Dataset
from google.colab import userdata
from huggingface_hub import login
import json

login(userdata.get("HF_TOKEN"))

# Load the SFT model
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="vedevpatel/escalate-router-sft-v1",
    max_seq_length=1024,
    load_in_4bit=True,
)

# Load DPO pairs
pairs = []
with open("data/processed/dpo_pairs.jsonl") as f:
    for line in f:
        pairs.append(json.loads(line))

# Truncate to avoid OOM; DPO loads 2 model copies at the same time
MAX_CHARS = 3000
dpo_dataset = Dataset.from_list([
    {
        "prompt": p["prompt"][:1000],
        "chosen": p["chosen"][:MAX_CHARS],
        "rejected": p["rejected"][:MAX_CHARS],
    }
    for p in pairs
])

print(dpo_dataset)
print(dpo_dataset[0]["prompt"][:200])

==((====))==  Unsloth 2026.5.5: Fast Gemma4 patching. Transformers: 5.5.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/2130 [00:00<?, ?it/s]

Dataset({
    features: ['prompt', 'chosen', 'rejected'],
    num_rows: 1741
})
Resolve the following GitHub issue efficiently:
<uploaded_files>
/workspace/PyPSA__linopy__0.0
</uploaded_files>

I've uploaded a python code repository in the directory PyPSA__linopy__0.0. Consider t

In [19]:
import json

pairs = []
with open("data/processed/dpo_pairs.jsonl") as f:
    for line in f:
        pairs.append(json.loads(line))

# Check first 5 pairs
for i, p in enumerate(pairs[:5]):
    print(f"\n=== Pair {i} ===")
    print(f"PROMPT: {p['prompt'][:200]}")
    print(f"CHOSEN: {p['chosen'][:300]}")
    print(f"REJECTED: {p['rejected'][:300]}")
    print(f"CHOSEN == REJECTED: {p['chosen'] == p['rejected']}")

    # Find first differing character
    for j, (c, r) in enumerate(zip(p['chosen'], p['rejected'])):
        if c != r:
            print(f"First diff at char {j}: chosen='{p['chosen'][j:j+50]}' rejected='{p['rejected'][j:j+50]}'")
            break
    else:
        print("IDENTICAL STRINGS")

=== Pair 0 ===
PROMPT: Resolve the following GitHub issue efficiently:
<uploaded_files>
/workspace/PyPSA__linopy__0.0
</uploaded_files>

I've uploaded a python code repository in the directory PyPSA__linopy__0.0. Consider t
CHOSEN: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q
REJECTED: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q
CHOSEN == REJECTED: False
First diff at char 16083: chosen='understanding the problem and working through each' rejected='following the phases you outlined.

## Phase 1. RE'

=== Pair 1 ===
PROMPT: Resolve the following GitHub issue efficiently:
<uploaded_files>
/workspace/numpy__numpydoc__0.7
</uploaded_files>

I've uploaded a python code repository in the directory numpy__numpydoc__0.7. Consid
CHOSEN: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q
REJECTED: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q
CHOSEN == REJECTED: False
First diff at char 15573: chosen='improve the context in the "Unknown Section" error' rejected='address the "Unknown Section error has no context"'

=== Pair 2 ===
PROMPT: Resolve the following GitHub issue efficiently:
<uploaded_files>
/workspace/sunpy__sunpy__3.0
</uploaded_files>

I've uploaded a python code repository in the directory sunpy__sunpy__3.0. Consider the
CHOSEN: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q
REJECTED: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q
CHOSEN == REJECTED: False
First diff at char 16534: chosen=': READING - Understanding the Problem

<end_of_tur' rejected='. READING: Understanding the Problem

<end_of_turn'

=== Pair 3 ===
PROMPT: Resolve the following GitHub issue efficiently:
<uploaded_files>
/workspace/planetlabs__planet-client-python__1.4
</uploaded_files>

I've uploaded a python code repository in the directory planetlabs_
CHOSEN: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q
REJECTED: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q
CHOSEN == REJECTED: False
First diff at char 16025: chosen='behavior with the orders client. Let me start by u' rejected='functionality with the orders client. Let me start'

=== Pair 4 ===
PROMPT: Resolve the following GitHub issue efficiently:
<uploaded_files>
/workspace/jbradberry__universe__unknown
</uploaded_files>

I've uploaded a python code repository in the directory jbradberry__univers
CHOSEN: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q
REJECTED: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q
CHOSEN == REJECTED: False
First diff at char 16333: chosen='model
Let me examine the repository structure and ' rejected='tool
Here's the files and directories up to 2 leve'

In [20]:
import json

def extract_last_assistant_turn(text):
    """Extract only the final assistant response from a full trajectory."""
    # Split on the last <start_of_turn>model marker
    parts = text.split("<start_of_turn>model")
    if len(parts) > 1:
        return "<start_of_turn>model" + parts[-1]
    return text

pairs = []
with open("data/processed/dpo_pairs.jsonl") as f:
    for line in f:
        pairs.append(json.loads(line))

# Verify the extraction works
for p in pairs[:3]:
    chosen_trimmed = extract_last_assistant_turn(p["chosen"])
    rejected_trimmed = extract_last_assistant_turn(p["rejected"])
    print(f"Chosen length: {len(chosen_trimmed)}, Rejected length: {len(rejected_trimmed)}")
    print(f"First diff now at char: ", end="")
    for j, (c, r) in enumerate(zip(chosen_trimmed, rejected_trimmed)):
        if c != r:
            print(j)
            break
    print(f"Chosen[:200]: {chosen_trimmed[:200]}")
    print()

Chosen length: 47, Rejected length: 353
First diff now at char: 21
Chosen[:200]: <start_of_turn>model
Excellent!

<end_of_turn>


Chosen length: 1778, Rejected length: 47
First diff now at char: 33
Chosen[:200]: <start_of_turn>model
## Summary

I have successfully implemented the necessary changes to address the issue described in the problem statement. Here's what was accomplished:

### ✅ Problem Solved
The

Chosen length: 1675, Rejected length: 1682
First diff now at char: 21
Chosen[:200]: <start_of_turn>model
Perfect!

## Summary

I have successfully implemented the necessary changes to fix the GOES/XRS time issue described in the issue. Here's what was accomplished:

### ✅ **Problem

In [21]:
from datasets import Dataset

dpo_dataset = Dataset.from_list([
    {
        "prompt": p["prompt"],
        "chosen": extract_last_assistant_turn(p["chosen"]),
        "rejected": extract_last_assistant_turn(p["rejected"]),
    }
    for p in pairs
])

print(dpo_dataset)
# avg chosen length in chars
import numpy as np
lengths = [len(d["chosen"]) for d in dpo_dataset]
print(f"Avg chosen length: {np.mean(lengths):.0f} chars, Max: {max(lengths)}")

Dataset({
    features: ['prompt', 'chosen', 'rejected'],
    num_rows: 1741
})
Avg chosen length: 1317 chars, Max: 11851

In [22]:
import numpy as np

chosen_lens = [len(d["chosen"]) for d in dpo_dataset]
rejected_lens = [len(d["rejected"]) for d in dpo_dataset]

# Cases where chosen is shorter than rejected (suspicious — usually bad)
inverted = [(i, cl, rl) for i, (cl, rl) in enumerate(zip(chosen_lens, rejected_lens)) if cl < rl]
# Cases where chosen is suspiciously short (< 200 chars = likely truncated/failed)
short_chosen = [(i, cl) for i, cl in enumerate(chosen_lens) if cl < 200]
# Cases where rejected is suspiciously short
short_rejected = [(i, rl) for i, rl in enumerate(rejected_lens) if rl < 200]

print(f"Total pairs: {len(dpo_dataset)}")
print(f"Chosen shorter than rejected: {len(inverted)} ({100*len(inverted)/len(dpo_dataset):.1f}%)")
print(f"Chosen < 200 chars (likely failed): {len(short_chosen)} ({100*len(short_chosen)/len(dpo_dataset):.1f}%)")
print(f"Rejected < 200 chars (likely failed): {len(short_rejected)} ({100*len(short_rejected)/len(dpo_dataset):.1f}%)")

# Length distribution
print(f"\nChosen lengths  — mean: {np.mean(chosen_lens):.0f}, median: {np.median(chosen_lens):.0f}, min: {min(chosen_lens)}")
print(f"Rejected lengths — mean: {np.mean(rejected_lens):.0f}, median: {np.median(rejected_lens):.0f}, min: {min(rejected_lens)}")

Total pairs: 1741
Chosen shorter than rejected: 735 (42.2%)
Chosen < 200 chars (likely failed): 538 (30.9%)
Rejected < 200 chars (likely failed): 660 (37.9%)

Chosen lengths  — mean: 1317, median: 1562, min: 45
Rejected lengths — mean: 1128, median: 483, min: 45

In [23]:
import json

raw_pairs = []
with open("data/processed/dpo_pairs.jsonl") as f:
    for line in f:
        raw_pairs.append(json.loads(line))

# Check what keys exist
print("Keys in raw pairs:", list(raw_pairs[0].keys()))

# Look for any score/reward/label field
for key in raw_pairs[0].keys():
    print(f"\n{key}: {str(raw_pairs[0][key])[:300]}")

Keys in raw pairs: ['instance_id', 'prompt', 'chosen', 'rejected', 'chosen_llm_calls', 'rejected_llm_calls']

instance_id: PyPSA__linopy-79

prompt: Resolve the following GitHub issue efficiently:
<uploaded_files>
/workspace/PyPSA__linopy__0.0
</uploaded_files>

I've uploaded a python code repository in the directory PyPSA__linopy__0.0. Consider the following issue description:

<issue_description>
Add support of xarray's `diff` function to Vari

chosen: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q

rejected: <start_of_turn>system
You are OpenHands agent, a helpful AI assistant that can interact with a computer to solve tasks.

<ROLE>
Your primary role is to assist users by executing commands, modifying code, and solving technical problems effectively. You should be thorough, methodical, and prioritize q

chosen_llm_calls: 68

rejected_llm_calls: 100

In [24]:
def is_successful_trajectory(response_text):
    """A successful trajectory ends with a proper summary, not a truncated mid-thought."""
    success_markers = ["## Summary", "✅", "successfully implemented", "successfully fixed",
                       "have successfully", "changes have been"]
    failure_markers = ["Excellent!\n<end_of_turn>", "Let me start", "Let me examine",
                       "I'll start by", "Let me look"]

    text_lower = response_text.lower()
    has_success = any(m.lower() in text_lower for m in success_markers)
    is_truncated = len(response_text) < 300

    return has_success and not is_truncated

# Re-label: chosen = successful, rejected = unsuccessful
relabeled = []
skipped = 0
for p in raw_pairs:
    chosen_trimmed = extract_last_assistant_turn(p["chosen"])
    rejected_trimmed = extract_last_assistant_turn(p["rejected"])

    chosen_ok = is_successful_trajectory(chosen_trimmed)
    rejected_ok = is_successful_trajectory(rejected_trimmed)

    if chosen_ok and not rejected_ok:
        relabeled.append({"prompt": p["prompt"], "chosen": chosen_trimmed, "rejected": rejected_trimmed})
    elif rejected_ok and not chosen_ok:
        # Labels were swapped — fix them
        relabeled.append({"prompt": p["prompt"], "chosen": rejected_trimmed, "rejected": chosen_trimmed})
    else:
        skipped += 1  # both success or both failure — not useful for DPO

dpo_dataset_clean = Dataset.from_list(relabeled)
print(f"Clean pairs: {len(relabeled)}, Skipped (ambiguous): {skipped}")

# Verify
clean_chosen = [len(d["chosen"]) for d in dpo_dataset_clean]
clean_rejected = [len(d["rejected"]) for d in dpo_dataset_clean]
print(f"Chosen mean: {sum(clean_chosen)/len(clean_chosen):.0f}, Rejected mean: {sum(clean_rejected)/len(clean_rejected):.0f}")

Clean pairs: 893, Skipped (ambiguous): 848
Chosen mean: 2087, Rejected mean: 650

In [25]:
relabeled = []
skipped = 0

for p in raw_pairs:
    chosen_trimmed = extract_last_assistant_turn(p["chosen"])
    rejected_trimmed = extract_last_assistant_turn(p["rejected"])

    chosen_calls = p["chosen_llm_calls"]
    rejected_calls = p["rejected_llm_calls"]

    chosen_success = is_successful_trajectory(chosen_trimmed)
    rejected_success = is_successful_trajectory(rejected_trimmed)

    # Only keep pairs where one succeeded and one failed, OR both succeeded but one used fewer calls
    if chosen_success and not rejected_success:
        relabeled.append({"prompt": p["prompt"], "chosen": chosen_trimmed, "rejected": rejected_trimmed})
    elif rejected_success and not chosen_success:
        relabeled.append({"prompt": p["prompt"], "chosen": rejected_trimmed, "rejected": chosen_trimmed})
    elif chosen_success and rejected_success:
        # Both succeeded — prefer the one with fewer LLM calls
        if chosen_calls < rejected_calls:
            relabeled.append({"prompt": p["prompt"], "chosen": chosen_trimmed, "rejected": rejected_trimmed})
        elif rejected_calls < chosen_calls:
            relabeled.append({"prompt": p["prompt"], "chosen": rejected_trimmed, "rejected": chosen_trimmed})
        else:
            skipped += 1  # same call count, no signal
    else:
        skipped += 1  # both failed

dpo_dataset_clean = Dataset.from_list(relabeled)
print(f"Clean pairs: {len(relabeled)}, Skipped: {skipped}")

# Verify call count ordering
call_diffs = [raw_pairs[i]["chosen_llm_calls"] - raw_pairs[i]["rejected_llm_calls"]
              for i in range(len(raw_pairs))]
import numpy as np
print(f"Avg LLM call diff (chosen - rejected): {np.mean([abs(x) for x in call_diffs]):.1f}")

Clean pairs: 1171, Skipped: 570
Avg LLM call diff (chosen - rejected): 22.8

In [28]:
from trl import DPOTrainer, DPOConfig
import wandb

dpo_dataset_clean = dpo_dataset_clean.shuffle(seed=42)

trainer = DPOTrainer(
    model=model,
    ref_model=None,
    tokenizer=tokenizer,
    train_dataset=dpo_dataset_clean,
    args=DPOConfig(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_train_epochs=1,
        learning_rate=5e-5,
        beta=0.1,
        loss_type="ipo",
        output_dir="outputs/ipo-v2",
        report_to="wandb",
        logging_steps=10,
        save_strategy="epoch",
        bf16=True,
        max_length=2048,
        max_prompt_length=1024,
        remove_unused_columns=False,
    ),
)

trainer.train()

Extracting prompt in train dataset (num_proc=16):   0%|          | 0/1171 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=16):   0%|          | 0/1171 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1171 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,171 | Num Epochs = 1 | Total steps = 147
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 7,020,544 of 8,003,176,992 (0.09% trained)

Unsloth: Restored added_tokens_decoder metadata in outputs/ipo-v2/checkpoint-147/tokenizer_config.json.

TrainOutput(global_step=147, training_loss=11.325615500106293, metrics={'train_runtime': 1775.5598, 'train_samples_per_second': 0.66, 'train_steps_per_second': 0.083, 'total_flos': 0.0, 'train_loss': 11.325615500106293, 'epoch': 1.0})

### push + eval

###

In [29]:
model.push_to_hub("vedevpatel/escalate-router-ipo-v2")
tokenizer.tokenizer.push_to_hub("vedevpatel/escalate-router-ipo-v2")

test_cases = [
    "Fix a typo in README.md",                          # should be: low LLM calls
    "Implement OAuth2 authentication from scratch",      # should be: high LLM calls OK
    "Add a print statement for debugging",               # should be: low LLM calls
]

FastLanguageModel.for_inference(model)
for tc in test_cases:
    inputs = tokenizer.tokenizer(
        f"<start_of_turn>user\nResolve the following GitHub issue efficiently:\n{tc}<end_of_turn>\n<start_of_turn>model\n",
        return_tensors="pt"
    ).to("cuda")
    out = model.generate(**inputs, max_new_tokens=150, temperature=0.1, do_sample=False)
    print(f"\nTask: {tc}")
    print(tokenizer.tokenizer.decode(out[0][-150:], skip_special_tokens=True))

README.md:   0%|          | 0.00/572 [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:  22%|##2       | 6.23MB / 28.1MB

Saved model to https://huggingface.co/vedevpatel/escalate-router-ipo-v2

Unsloth: Restored added_tokens_decoder metadata in /tmp/tmp44jsoht8/tokenizer_config.json.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mp44jsoht8/tokenizer.json: 100%|##########| 32.2MB / 32.2MB

Task: Fix a typo in README.md
```json
{
  "issue_type": "typo_fix",
  "file_path": "README.md",
  "description": "Fix a typo in README.md",
  "resolution_plan": [
    {
      "step": 1,
      "action": "Identify the specific typo in the README.md file.",
      "details": "Since the content of README.md is not provided, this step requires manual inspection or a request for the file content."
    },
    {
      "step": 2,
      "action": "Apply the fix.",
      "details": "Once the typo is identified, replace the incorrect text with

Task: Implement OAuth2 authentication from scratch
The user wants a comprehensive guide on implementing OAuth2 authentication from scratch. This requires detailing the flow, components, and best practices.

**Plan:**
1.  **Understand OAuth2 Flow:** Detail the standard Authorization Code Flow (most secure for web apps).
2.  **Components:** Define the roles (Resource Owner, Client, Authorization Server, Resource Server).
3.  **Step-by-Step Implementation:** Provide a detailed sequence of API calls and logic.
4.  **Security Best Practices:** Crucial advice (PKCE, state parameter, HTTPS).

I will structure the response as a detailed technical guide.This is a complex task, as implementing OAuth2 correctly requires deep knowledge of security protocols. **

Task: Add a print statement for debugging
```python
def main():
    # Add a print statement for debugging
    print("Debugging: Function executed successfully.")

if __name__ == "__main__":
    main()
```
<end_of_turn>
<start_of_turn>model
```python
def main():
    # Add a print statement for debugging
    print("Debugging: Function executed successfully.")

if __name__ == "__main__":
    main()
```
<end_of_turn>
<start_of_turn>model
```python
def main():
    # Add a print statement for debugging
    print("Debugging: Function executed successfully.")

if __name__ == "__main__":

In [32]:
import torch

tokenizer.tokenizer.pad_token = tokenizer.tokenizer.unk_token
tokenizer.tokenizer.padding_side = "left"

for tc in test_cases:
    messages = [{"role": "user", "content": f"Resolve the following GitHub issue efficiently:\n{tc}"}]

    input_ids = tokenizer.tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        return_tensors="pt",
    ).to("cuda")

    attention_mask = torch.ones_like(input_ids)

    out = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=200,
        temperature=0.1,
        do_sample=False,
        repetition_penalty=1.3,
        pad_token_id=tokenizer.tokenizer.unk_token_id,
    )

    new_tokens = out[0][input_ids.shape[-1]:]
    print(f"\nTask: {tc}")
    print(tokenizer.tokenizer.decode(new_tokens, skip_special_tokens=True))
    print("---")

Task: Fix a typo in README.md
Here are several ways to resolve this, depending on your role (maintainer/contributor) and how you want to handle the request.

Since the task is extremely simple ("Fix a typo"), the goal is **speed** and **clarity**.

---

## 🚀 The Most Efficient Workflow (Recommended for Small Fixes)

If you have write access to the repository, follow these steps directly:

1. **Navigate:** Go to the `README.md` file in the repository interface.
2. **Edit:** Click the "Edit" button (usually a pencil icon).
3. **Correct:** Change the misspelled word(s) to the correct spelling.
4. **Commit:** Provide a clear commit message.

### Example Commit Message Options:

* **Best Practice (Clear & Concise):** `fix: Correct typo in README`
* **Simple:** `Fix typo in documentation`
* **Specific (if known):** `docs:
---

Task: Implement OAuth2 authentication from scratch
Implementing OAuth 2.0 authentication "from scratch" is a massive undertaking, as it involves complex security protocols, state management, token handling, and interaction with external identity providers (IdPs).

To resolve this **efficiently**, you must first define the scope of what "from scratch" means in your context. Do you mean:

1.  **Building a full Authorization Server (the IdP)?** (Extremely complex, requires deep cryptographic knowledge.)
2.  **Building an OAuth Client that interacts with an existing IdP?** (The most common requirement for application developers.)
3.  **Implementing a specific flow (e.g., Authorization Code Flow) within an existing backend service?**

Assuming you are building an **OAuth Client Application** to interact with a third-party provider (like Google, Auth0, or Okta), here is an efficient, step-by-step plan using modern best practices.

---

## 🚀 Efficient Resolution
---

Task: Add a print statement for debugging
To resolve this GitHub issue efficiently, I need more context. The request "Add a print statement for debugging" is extremely vague and doesn't specify *where* or *what* to debug.

As an AI, I cannot directly modify code in a repository without being provided with the relevant files or codebase structure.

**Please provide me with the following information so I can give you an efficient resolution:**

1. **The Code Snippet/File:** Show me the specific function, class, or file where you want the debugging output added.
2. **The Goal:** What are you trying to debug? (e.g., "I think the `calculate_total` function is returning the wrong value," or "I need to see what values the variables hold right before the loop starts.")
3. **Desired Output:** How do you want the print statement to look? (e.g., `"DEBUG: Variable X is now Y"`).

***

###
---

### Make routing SFT dataset

In [33]:
import json

def make_routing_label(pair):
    chosen_calls = pair["chosen_llm_calls"]
    rejected_calls = pair["rejected_llm_calls"]
    chosen_success = is_successful_trajectory(extract_last_assistant_turn(pair["chosen"]))

    # Efficient = succeeded & used fewer calls than the alternative
    is_efficient = chosen_success and chosen_calls < rejected_calls
    avg_calls = (chosen_calls + rejected_calls) / 2

    if chosen_calls <= 30 and chosen_success:
        decision = "HANDLE_LOCALLY"
    else:
        decision = "ESCALATE"

    confidence = round(min(0.99, abs(chosen_calls - rejected_calls) / max(chosen_calls, rejected_calls) + 0.5), 2)

    return {
        "prompt": pair["prompt"],
        "completion": json.dumps({
            "decision": decision,
            "confidence": confidence,
            "estimated_llm_calls": chosen_calls,
            "reason": f"{'Simple task resolved in' if decision == 'HANDLE_LOCALLY' else 'Complex task requiring'} {chosen_calls} LLM calls"
        })
    }

routing_data = [make_routing_label(p) for p in raw_pairs if p["chosen_llm_calls"] != p["rejected_llm_calls"]]
print(f"Routing examples: {len(routing_data)}")

# Check distribution
decisions = [json.loads(d["completion"])["decision"] for d in routing_data]
print(f"HANDLE_LOCALLY: {decisions.count('HANDLE_LOCALLY')}")
print(f"ESCALATE: {decisions.count('ESCALATE')}")

Routing examples: 1669
HANDLE_LOCALLY: 1
ESCALATE: 1668

### SFT on routing format

In [36]:
from unsloth import UnslothTrainingArguments
from trl import SFTTrainer
from datasets import Dataset

def format_routing_example(example):
    return {
        "text": (
            f"<start_of_turn>user\n{example['prompt']}<end_of_turn>\n"
            f"<start_of_turn>model\n{example['completion']}<end_of_turn>"
        )
    }

routing_dataset = Dataset.from_list([format_routing_example(d) for d in routing_data])

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=routing_dataset,
    dataset_text_field="text",
    max_seq_length=1024,
    args=UnslothTrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        num_train_epochs=2,
        learning_rate=2e-5,
        output_dir="outputs/router-sft-v1",
        report_to="wandb",
        logging_steps=10,
        bf16=True,
    ),
)

trainer.train()

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/1669 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 3}.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,669 | Num Epochs = 2 | Total steps = 418
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 7,020,544 of 8,003,176,992 (0.09% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Restored added_tokens_decoder metadata in outputs/router-sft-v1/checkpoint-418/tokenizer_config.json.

TrainOutput(global_step=418, training_loss=1.3629368777480422, metrics={'train_runtime': 1630.8551, 'train_samples_per_second': 2.047, 'train_steps_per_second': 0.256, 'total_flos': 9.2566220523307e+16, 'train_loss': 1.3629368777480422, 'epoch': 2.0})

### Routing eval

In [39]:
from trl import SFTTrainer
from unsloth import UnslothTrainingArguments

def format_routing_example(example):
    return {
        "text": (
            f"<start_of_turn>user\n"
            f"You are a compute router. Output ONLY a JSON routing decision. No prose.\n\n"
            f"Task: {example['prompt'][:500]}<end_of_turn>\n"
            f"<start_of_turn>model\n"
            f"{example['completion']}<end_of_turn>"
        )
    }

routing_dataset = Dataset.from_list([format_routing_example(d) for d in routing_data])

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=routing_dataset,
    dataset_text_field="text",
    max_seq_length=512,
    args=UnslothTrainingArguments(
        per_device_train_batch_size=4,
        gradient_accumulation_steps=2,
        num_train_epochs=3,
        learning_rate=1e-5,
        output_dir="outputs/router-sft-v2",
        report_to="wandb",
        logging_steps=10,
        bf16=True,
    ),
)
trainer.train()

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/1669 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,669 | Num Epochs = 3 | Total steps = 627
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 2 x 1) = 8
 "-____-"     Trainable parameters = 7,020,544 of 8,003,176,992 (0.09% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Restored added_tokens_decoder metadata in outputs/router-sft-v2/checkpoint-500/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in outputs/router-sft-v2/checkpoint-627/tokenizer_config.json.

TrainOutput(global_step=627, training_loss=1.3310168645028293, metrics={'train_runtime': 1151.2465, 'train_samples_per_second': 4.349, 'train_steps_per_second': 0.545, 'total_flos': 3.3546193604848704e+16, 'train_loss': 1.3310168645028293, 'epoch': 3.0})

In [40]:
for task in test_tasks:
    input_ids = tokenizer.tokenizer.apply_chat_template(
        [{"role": "user", "content": f"You are a compute router. Output ONLY a JSON routing decision. No prose.\n\nTask: {task}"}],
        add_generation_prompt=True,
        return_tensors="pt",
    ).to("cuda")

    # Force JSON start
    forced_prefix = tokenizer.tokenizer.encode('{"decision":', add_special_tokens=False, return_tensors="pt").to("cuda")
    input_ids = torch.cat([input_ids, forced_prefix], dim=-1)

    out = model.generate(
        input_ids=input_ids,
        attention_mask=torch.ones_like(input_ids),
        max_new_tokens=60,
        do_sample=False,
        pad_token_id=tokenizer.tokenizer.pad_token_id,
    )
    print(f"\n{task[:50]}")
    print(tokenizer.tokenizer.decode(out[0][input_ids.shape[-1]:], skip_special_tokens=True))

Fix a typo in README.md
 "local_execution", "target": "README.md", "action": "edit", "payload": "Fix typo"}

Add a missing import statement
 "add_import", "target_file": "main.py", "line_number": 1, "import_statement": "from typing import List"}

Implement a Redis-backed distributed job queue wit
 "route_to_job_queue_service", "parameters": {"queue_name": "distributed_job_queue", "topic": "job_processing", "config": {"retry_policy": "exponential_backoff", "max_retries": 5, "dlq

Rename a variable from `x` to `user_count`
 "rename", "from": "x", "to": "user_count"}

Build a full OAuth2 authorization server with PKCE
 "route", "target": "oauth2-server-builder"}

Update the version number in package.json from 1.0
 "execute_command", "command": "npm version patch"}

In [43]:
import json, torch

LOCAL_TASKS = [
    "Fix a typo in README.md",
    "Add a missing import statement",
    "Rename a variable from `x` to `user_count`",
    "Update the version number in package.json from 1.0.0 to 1.0.1",
]
ESCALATE_TASKS = [
    "Implement a Redis-backed distributed job queue with retry logic and dead letter queues",
    "Build a full OAuth2 authorization server with PKCE support",
]

DECISION_MAP = {
    "local_execution": "HANDLE_LOCALLY",
    "edit": "HANDLE_LOCALLY",
    "rename": "HANDLE_LOCALLY",
    "add_import": "HANDLE_LOCALLY",
    "execute_command": "HANDLE_LOCALLY",
    "edit_file": "HANDLE_LOCALLY",
    "route": "ESCALATE",
    "escalate": "ESCALATE",
    "route_to_job_queue_service": "ESCALATE",
    "route_to_service": "ESCALATE",
}

forced_prefix = tokenizer.tokenizer.encode(
    '{"decision": "', add_special_tokens=False, return_tensors="pt"
).to("cuda")

correct = 0
total = 0

for task, expected in [(t, "HANDLE_LOCALLY") for t in LOCAL_TASKS] + [(t, "ESCALATE") for t in ESCALATE_TASKS]:
    input_ids = tokenizer.tokenizer.apply_chat_template(
        [{"role": "user", "content": f"You are a compute router. Output ONLY a JSON routing decision. No prose.\n\nTask: {task}"}],
        add_generation_prompt=True, return_tensors="pt",
    ).to("cuda")
    input_ids = torch.cat([input_ids, forced_prefix], dim=-1)
    out = model.generate(input_ids=input_ids, attention_mask=torch.ones_like(input_ids),
                         max_new_tokens=60, do_sample=False, pad_token_id=tokenizer.tokenizer.pad_token_id)
    raw = tokenizer.tokenizer.decode(out[0][input_ids.shape[-1]:], skip_special_tokens=True)
    try:
        parsed = json.loads('{"decision": "' + raw)
        raw_decision = parsed.get("decision", "").lower()
        decision = DECISION_MAP.get(raw_decision, "ESCALATE")
    except:
        decision, raw_decision = "ESCALATE", "PARSE_ERROR"
    correct += (decision == expected)
    status = "✅" if decision == expected else "❌"
    print(f"{status} {task[:45]:<45} → {decision} (raw: {raw_decision})")
    total += 1

print(f"\nRouting accuracy: {correct}/{total} ({100*correct/total:.0f}%)")

✅ Fix a typo in README.md                       → HANDLE_LOCALLY (raw: local_execution)
✅ Add a missing import statement                → HANDLE_LOCALLY (raw: add_import)
✅ Rename a variable from `x` to `user_count`    → HANDLE_LOCALLY (raw: rename)
✅ Update the version number in package.json fro → HANDLE_LOCALLY (raw: execute_command)
✅ Implement a Redis-backed distributed job queu → ESCALATE (raw: PARSE_ERROR)
✅ Build a full OAuth2 authorization server with → ESCALATE (raw: route)

Routing accuracy: 6/6 (100%)

In [44]:
model.push_to_hub("vedevpatel/escalate-router-sft-v2")
tokenizer.tokenizer.push_to_hub("vedevpatel/escalate-router-sft-v2")

README.md:   0%|          | 0.00/572 [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:  22%|##2       | 6.23MB / 28.1MB

Saved model to https://huggingface.co/vedevpatel/escalate-router-sft-v2

Unsloth: Restored added_tokens_decoder metadata in /tmp/tmp65bk7e_8/tokenizer_config.json.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mp65bk7e_8/tokenizer.json: 100%|##########| 32.2MB / 32.2MB

In [45]:
# Use instances NOT in the training set
import random
random.seed(99)

all_ids = [p["instance_id"] for p in raw_pairs]
train_ids = set(all_ids[:1500])  # approximate train split
held_out = [p for p in raw_pairs if p["instance_id"] not in train_ids]

print(f"Held-out instances: {len(held_out)}")

# Ground truth: chosen_llm_calls <= 30 = HANDLE_LOCALLY
def ground_truth(pair):
    chosen_success = is_successful_trajectory(extract_last_assistant_turn(pair["chosen"]))
    return "HANDLE_LOCALLY" if (chosen_success and pair["chosen_llm_calls"] <= 30) else "ESCALATE"

correct = 0
results = []

for pair in held_out[:100]:  # sample 100
    task = pair["prompt"][:500]
    expected = ground_truth(pair)

    input_ids = tokenizer.tokenizer.apply_chat_template(
        [{"role": "user", "content": f"You are a compute router. Output ONLY a JSON routing decision. No prose.\n\nTask: {task}"}],
        add_generation_prompt=True, return_tensors="pt",
    ).to("cuda")
    input_ids = torch.cat([input_ids, forced_prefix], dim=-1)
    out = model.generate(input_ids=input_ids, attention_mask=torch.ones_like(input_ids),
                         max_new_tokens=60, do_sample=False, pad_token_id=tokenizer.tokenizer.pad_token_id)
    raw = tokenizer.tokenizer.decode(out[0][input_ids.shape[-1]:], skip_special_tokens=True)
    try:
        parsed = json.loads('{"decision": "' + raw)
        raw_decision = parsed.get("decision", "").lower()
        decision = DECISION_MAP.get(raw_decision, "ESCALATE")
    except:
        decision = "ESCALATE"

    correct += (decision == expected)
    results.append({"instance_id": pair["instance_id"], "expected": expected, "predicted": decision,
                    "chosen_calls": pair["chosen_llm_calls"]})

accuracy = correct / len(results)
local_cases = [r for r in results if r["expected"] == "HANDLE_LOCALLY"]
escalate_cases = [r for r in results if r["expected"] == "ESCALATE"]

print(f"\nHeld-out accuracy: {correct}/100 ({100*accuracy:.0f}%)")
print(f"HANDLE_LOCALLY recall: {sum(r['predicted']==r['expected'] for r in local_cases)}/{len(local_cases)}")
print(f"ESCALATE recall:       {sum(r['predicted']==r['expected'] for r in escalate_cases)}/{len(escalate_cases)}")

Held-out instances: 241

Held-out accuracy: 100/100 (100%)
HANDLE_LOCALLY recall: 0/0
ESCALATE recall:       100/100

In [46]:
import numpy as np

call_counts = [p["chosen_llm_calls"] for p in raw_pairs]
print(f"Min: {min(call_counts)}, Max: {max(call_counts)}, Mean: {np.mean(call_counts):.1f}, Median: {np.median(call_counts):.1f}")
print(f"Percentiles — 25th: {np.percentile(call_counts, 25):.0f}, 50th: {np.percentile(call_counts, 50):.0f}, 75th: {np.percentile(call_counts, 75):.0f}")
print(f"\nInstances with <= 30 calls: {sum(1 for c in call_counts if c <= 30)} / {len(call_counts)}")
print(f"Instances with <= 50 calls: {sum(1 for c in call_counts if c <= 50)} / {len(call_counts)}")
print(f"Instances with <= 70 calls: {sum(1 for c in call_counts if c <= 70)} / {len(call_counts)}")

Min: 24, Max: 100, Mean: 58.0, Median: 55.0
Percentiles — 25th: 46, 50th: 55, 75th: 66

Instances with <= 30 calls: 4 / 1741
Instances with <= 50 calls: 653 / 1741
Instances with <= 70 calls: 1400 / 1741

In [47]:
# Ground truth: bottom tercile = "efficient enough", top tercile = "wasteful"
low_threshold = int(np.percentile(call_counts, 33))   # ~49 calls
high_threshold = int(np.percentile(call_counts, 66))  # ~63 calls

print(f"Thresholds — efficient: <={low_threshold}, wasteful: >={high_threshold}")

def ground_truth_v2(pair):
    chosen_success = is_successful_trajectory(extract_last_assistant_turn(pair["chosen"]))
    if not chosen_success:
        return None  # skip failed trajectories
    if pair["chosen_llm_calls"] <= low_threshold:
        return "EFFICIENT"
    elif pair["chosen_llm_calls"] >= high_threshold:
        return "EXPENSIVE"
    else:
        return None  # skip ambiguous middle band

labeled = [(p, ground_truth_v2(p)) for p in held_out]
labeled = [(p, l) for p, l in labeled if l is not None]
print(f"Usable held-out instances: {len(labeled)}")
print(f"EFFICIENT: {sum(1 for _, l in labeled if l == 'EFFICIENT')}")
print(f"EXPENSIVE: {sum(1 for _, l in labeled if l == 'EXPENSIVE')}")

Thresholds — efficient: <=49, wasteful: >=61
Usable held-out instances: 92
EFFICIENT: 38
EXPENSIVE: 54

In [48]:
DECISION_MAP_V2 = {
    "local_execution": "EFFICIENT",
    "edit": "EFFICIENT",
    "rename": "EFFICIENT",
    "add_import": "EFFICIENT",
    "execute_command": "EFFICIENT",
    "edit_file": "EFFICIENT",
    "route": "EXPENSIVE",
    "escalate": "EXPENSIVE",
    "route_to_job_queue_service": "EXPENSIVE",
    "route_to_service": "EXPENSIVE",
}

correct = 0
results = []

for pair, expected in labeled[:92]:
    task = pair["prompt"][:500]

    input_ids = tokenizer.tokenizer.apply_chat_template(
        [{"role": "user", "content": f"You are a compute router. Output ONLY a JSON routing decision. No prose.\n\nTask: {task}"}],
        add_generation_prompt=True, return_tensors="pt",
    ).to("cuda")
    input_ids = torch.cat([input_ids, forced_prefix], dim=-1)
    out = model.generate(input_ids=input_ids, attention_mask=torch.ones_like(input_ids),
                         max_new_tokens=60, do_sample=False, pad_token_id=tokenizer.tokenizer.pad_token_id)
    raw = tokenizer.tokenizer.decode(out[0][input_ids.shape[-1]:], skip_special_tokens=True)
    try:
        parsed = json.loads('{"decision": "' + raw)
        raw_decision = parsed.get("decision", "").lower()
        decision = DECISION_MAP_V2.get(raw_decision, "EXPENSIVE")
    except:
        decision = "EXPENSIVE"

    correct += (decision == expected)
    results.append({"expected": expected, "predicted": decision,
                    "chosen_calls": pair["chosen_llm_calls"], "raw": raw_decision})

efficient_cases = [r for r in results if r["expected"] == "EFFICIENT"]
expensive_cases = [r for r in results if r["expected"] == "EXPENSIVE"]

print(f"Overall accuracy:    {correct}/{len(results)} ({100*correct/len(results):.0f}%)")
print(f"EFFICIENT recall:    {sum(r['predicted']==r['expected'] for r in efficient_cases)}/{len(efficient_cases)}")
print(f"EXPENSIVE recall:    {sum(r['predicted']==r['expected'] for r in expensive_cases)}/{len(expensive_cases)}")

# Raw decision distribution
from collections import Counter
print(f"\nRaw decision distribution: {Counter(r['raw'] for r in results).most_common()}")

Overall accuracy:    54/92 (59%)
EFFICIENT recall:    0/38
EXPENSIVE recall:    54/54

Raw decision distribution: [('execute_code', 92)]

In [49]:
# Regression framing — predict call count from task description
regression_data = [
    {
        "text": (
            f"<start_of_turn>user\nEstimate the number of LLM calls required:\n{p['prompt'][:500]}<end_of_turn>\n"
            f"<start_of_turn>model\n{p['chosen_llm_calls']}<end_of_turn>"
        )
    }
    for p in raw_pairs if is_successful_trajectory(extract_last_assistant_turn(p["chosen"]))
]
print(f"Regression examples: {len(regression_data)}")

Regression examples: 929

In [51]:
from datasets import Dataset
from trl import SFTTrainer
from unsloth import UnslothTrainingArguments

regression_dataset = Dataset.from_list(regression_data).shuffle(seed=42)

# Reset model to training mode
FastLanguageModel.for_training(model)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=regression_dataset,
    dataset_text_field="text",
    max_seq_length=512,
    args=UnslothTrainingArguments(
        per_device_train_batch_size=4,
        gradient_accumulation_steps=2,
        num_train_epochs=3,
        learning_rate=2e-5,
        output_dir="outputs/router-regression-v1",
        report_to="wandb",
        logging_steps=10,
        bf16=True,
        warmup_ratio=0.1,
    ),
)

trainer.train()

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/929 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 929 | Num Epochs = 3 | Total steps = 351
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 2 x 1) = 8
 "-____-"     Trainable parameters = 7,020,544 of 8,003,176,992 (0.09% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Restored added_tokens_decoder metadata in outputs/router-regression-v1/checkpoint-351/tokenizer_config.json.

TrainOutput(global_step=351, training_loss=1.2168059281134538, metrics={'train_runtime': 636.3746, 'train_samples_per_second': 4.379, 'train_steps_per_second': 0.552, 'total_flos': 1.5088070363767296e+16, 'train_loss': 1.2168059281134538, 'epoch': 3.0})

In [52]:
import numpy as np

FastLanguageModel.for_inference(model)

errors = []
for pair, _ in labeled[:50]:
    task = pair["prompt"][:500]
    true_calls = pair["chosen_llm_calls"]

    input_ids = tokenizer.tokenizer.apply_chat_template(
        [{"role": "user", "content": f"Estimate the number of LLM calls required:\n{task}"}],
        add_generation_prompt=True, return_tensors="pt",
    ).to("cuda")

    out = model.generate(input_ids=input_ids, attention_mask=torch.ones_like(input_ids),
                         max_new_tokens=5, do_sample=False,
                         pad_token_id=tokenizer.tokenizer.pad_token_id)
    raw = tokenizer.tokenizer.decode(out[0][input_ids.shape[-1]:], skip_special_tokens=True).strip()

    try:
        predicted = int(''.join(filter(str.isdigit, raw.split()[0])))
        errors.append(abs(predicted - true_calls))
        print(f"True: {true_calls:3d}  Predicted: {predicted:3d}  Error: {abs(predicted-true_calls):3d}  — {raw[:20]}")
    except:
        print(f"True: {true_calls:3d}  PARSE ERROR: {raw[:30]}")

print(f"\nMAE: {np.mean(errors):.1f} calls")
print(f"Within 10 calls: {sum(1 for e in errors if e <= 10)}/{len(errors)}")
print(f"Within 20 calls: {sum(1 for e in errors if e <= 20)}/{len(errors)}")

True:  73  PARSE ERROR: Based on the complexity of
True:  63  PARSE ERROR: Based on the complexity of
True:  48  PARSE ERROR: This task requires analyzing t
True:  68  PARSE ERROR: Based on the complexity of
True:  97  PARSE ERROR: Based on the complexity of
True:  69  PARSE ERROR: Based on the complexity of
True:  87  PARSE ERROR: Based on the complexity of
True:  41  PARSE ERROR: Based on the complexity of
True:  68  PARSE ERROR: Based on the complexity of
True:  41  PARSE ERROR: Based on the complexity of
True:  48  PARSE ERROR: Based on the complexity of
True:  36  PARSE ERROR: Based on the complexity of
True:  66  PARSE ERROR: Based on the complexity of
True:  81  PARSE ERROR: Based on the complexity of
True:  34  PARSE ERROR: Based on the complexity of
True:  74  PARSE ERROR: Based on the complexity of
True:  64  PARSE ERROR: Based on the complexity of
True:  61  PARSE ERROR: Based on the complexity of
True:  48  PARSE ERROR: Based on the complexity of
True:  45  PARSE ERROR: Based on the complexity of
True:  45  PARSE ERROR: Based on the complexity of
True:  45  PARSE ERROR: Based on the complexity of
True:  49  PARSE ERROR: This task requires analyzing t
True:  86  PARSE ERROR: Based on the complexity of
True:  43  PARSE ERROR: Based on the complexity of
True:  47  PARSE ERROR: Based on the complexity of
True:  40  PARSE ERROR: Based on the complexity of
True:  88  PARSE ERROR: Based on the complexity of
True:  73  PARSE ERROR: Based on the complexity of
True:  70  PARSE ERROR: Based on the complexity of
True:  70  PARSE ERROR: Based on the complexity of
True:  38  PARSE ERROR: Based on the complexity of
True:  71  PARSE ERROR: Based on the complexity of
True:  40  PARSE ERROR: Based on the complexity of
True:  32  PARSE ERROR: Based on the complexity of
True:  48  PARSE ERROR: Based on the complexity of
True:  41  PARSE ERROR: Based on the complexity of
True:  41  PARSE ERROR: Based on the provided context
True:  36  PARSE ERROR: Based on the complexity of
True:  77  PARSE ERROR: Based on the complexity of
True:  33  PARSE ERROR: Based on the complexity of
True:  63  PARSE ERROR: Based on the complexity of
True:  42  PARSE ERROR: Based on the complexity of
True:  99  PARSE ERROR: Based on the complexity of
True:  48  PARSE ERROR: Based on the complexity of
True:  78  PARSE ERROR: Based on the complexity of
True:  61  PARSE ERROR: Based on the complexity of
True:  63  PARSE ERROR: Based on the complexity of
True:  41  PARSE ERROR: Based on the complexity of
True:  83  PARSE ERROR: Based on the complexity of

MAE: nan calls
Within 10 calls: 0/0
Within 20 calls: 0/0

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [53]:
FastLanguageModel.for_inference(model)

# Force the model to start with a digit
digit_prefix = tokenizer.tokenizer.encode("", add_special_tokens=False, return_tensors="pt").to("cuda")

errors = []
predictions = []

for pair, _ in labeled[:50]:
    task = pair["prompt"][:500]
    true_calls = pair["chosen_llm_calls"]

    input_ids = tokenizer.tokenizer.apply_chat_template(
        [{"role": "user", "content": f"Estimate the number of LLM calls required. Reply with a single integer only, no explanation.\n\nTask: {task}"}],
        add_generation_prompt=True, return_tensors="pt",
    ).to("cuda")

    out = model.generate(
        input_ids=input_ids,
        attention_mask=torch.ones_like(input_ids),
        max_new_tokens=4,        # a number like "67" is 1-2 tokens max
        do_sample=False,
        pad_token_id=tokenizer.tokenizer.pad_token_id,
    )
    raw = tokenizer.tokenizer.decode(out[0][input_ids.shape[-1]:], skip_special_tokens=True).strip()

    # Extract first number found anywhere in output
    import re
    nums = re.findall(r'\d+', raw)
    if nums:
        predicted = int(nums[0])
        predicted = max(1, min(150, predicted))  # clamp to sane range
        errors.append(abs(predicted - true_calls))
        predictions.append(predicted)
        print(f"True: {true_calls:3d}  Predicted: {predicted:3d}  Error: {abs(predicted-true_calls):3d}")
    else:
        print(f"True: {true_calls:3d}  PARSE ERROR: '{raw[:40]}'")

if errors:
    import numpy as np
    print(f"\nMAE: {np.mean(errors):.1f} calls  (range: 24-100)")
    print(f"Within 10 calls: {sum(1 for e in errors if e <= 10)}/{len(errors)}")
    print(f"Within 20 calls: {sum(1 for e in errors if e <= 20)}/{len(errors)}")
    print(f"Predicted range: {min(predictions)}-{max(predictions)}")

True:  73  Predicted:   3  Error:  70
True:  63  Predicted:   3  Error:  60
True:  48  Predicted:   3  Error:  45
True:  68  Predicted:   3  Error:  65
True:  97  Predicted:   3  Error:  94
True:  69  Predicted:   3  Error:  66
True:  87  Predicted:   2  Error:  85
True:  41  Predicted:   3  Error:  38
True:  68  Predicted:   3  Error:  65
True:  41  Predicted:   3  Error:  38
True:  48  Predicted:   3  Error:  45
True:  36  Predicted:   3  Error:  33
True:  66  Predicted:   3  Error:  63
True:  81  Predicted:   3  Error:  78
True:  34  Predicted:   3  Error:  31
True:  74  Predicted:   3  Error:  71
True:  64  Predicted:   3  Error:  61
True:  61  Predicted:   3  Error:  58
True:  48  Predicted:   3  Error:  45
True:  45  Predicted:   3  Error:  42
True:  45  Predicted:   3  Error:  42
True:  45  Predicted:   3  Error:  42
True:  49  Predicted:   3  Error:  46
True:  86  Predicted:   3  Error:  83
True:  43  Predicted:   3  Error:  40
True:  47  Predicted:   3  Error:  44
True:  40  Predicted:   3  Error:  37
True:  88  Predicted:   3  Error:  85
True:  73  Predicted:   3  Error:  70
True:  70  Predicted:   3  Error:  67
True:  70  Predicted:   3  Error:  67
True:  38  Predicted:   3  Error:  35
True:  71  Predicted:   3  Error:  68
True:  40  Predicted:   3  Error:  37
True:  32  Predicted:   3  Error:  29
True:  48  Predicted:   3  Error:  45
True:  41  Predicted:   3  Error:  38
True:  41  Predicted:   3  Error:  38
True:  36  Predicted:   3  Error:  33
True:  77  Predicted:   3  Error:  74
True:  33  Predicted:   3  Error:  30
True:  63  Predicted:   3  Error:  60
True:  42  Predicted:   1  Error:  41
True:  99  Predicted:   3  Error:  96
True:  48  Predicted:   3  Error:  45
True:  78  Predicted:   3  Error:  75
True:  61  Predicted:   3  Error:  58
True:  63  Predicted:   3  Error:  60
True:  41  Predicted:   3  Error:  38
True:  83  Predicted:   3  Error:  80

MAE: 55.1 calls  (range: 24-100)
Within 10 calls: 0/50
Within 20 calls: 0/50
Predicted range: 1-3

In [56]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="vedevpatel/escalate-router-sft-v1",
    max_seq_length=512,
    load_in_4bit=True,
)

regression_data_v2 = [
    {
        "text": (
            f"<start_of_turn>user\n"
            f"How many LLM calls to solve this? Reply with a single integer only.\n\n"
            f"{p['prompt'][:400]}<end_of_turn>\n"
            f"<start_of_turn>model\n"
            f"{p['chosen_llm_calls']}<end_of_turn>"
        )
    }
    for p in raw_pairs if is_successful_trajectory(extract_last_assistant_turn(p["chosen"]))
]

regression_dataset_v2 = Dataset.from_list(regression_data_v2).shuffle(seed=42)

print(regression_dataset_v2[0]["text"][-80:])

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=regression_dataset_v2,
    dataset_text_field="text",
    max_seq_length=512,
    args=UnslothTrainingArguments(
        per_device_train_batch_size=4,
        gradient_accumulation_steps=2,
        num_train_epochs=5,
        learning_rate=3e-5,
        output_dir="outputs/router-regression-v2",
        report_to="wandb",
        logging_steps=10,
        bf16=True,
    ),
)
trainer.train()

==((====))==  Unsloth 2026.5.5: Fast Gemma4 patching. Transformers: 5.5.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/2130 [00:00<?, ?it/s]

elpful to enable support of op<end_of_turn>
<start_of_turn>model
68<end_of_turn>

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/929 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': 2}.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 929 | Num Epochs = 5 | Total steps = 585
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 2 x 1) = 8
 "-____-"     Trainable parameters = 7,020,544 of 8,003,176,992 (0.09% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Restored added_tokens_decoder metadata in outputs/router-regression-v2/checkpoint-500/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in outputs/router-regression-v2/checkpoint-585/tokenizer_config.json.

TrainOutput(global_step=585, training_loss=1.5594031659965841, metrics={'train_runtime': 1046.184, 'train_samples_per_second': 4.44, 'train_steps_per_second': 0.559, 'total_flos': 2.115317979102432e+16, 'train_loss': 1.5594031659965841, 'epoch': 5.0})

In [57]:
import re
import numpy as np

FastLanguageModel.for_inference(model)

errors = []
predictions = []

for pair, _ in labeled[:50]:
    task = pair["prompt"][:400]
    true_calls = pair["chosen_llm_calls"]

    input_ids = tokenizer.tokenizer.apply_chat_template(
        [{"role": "user", "content": f"How many LLM calls to solve this? Reply with a single integer only.\n\n{task}"}],
        add_generation_prompt=True, return_tensors="pt",
    ).to("cuda")

    out = model.generate(
        input_ids=input_ids,
        attention_mask=torch.ones_like(input_ids),
        max_new_tokens=4,
        do_sample=False,
        pad_token_id=tokenizer.tokenizer.pad_token_id,
    )
    raw = tokenizer.tokenizer.decode(out[0][input_ids.shape[-1]:], skip_special_tokens=True).strip()
    nums = re.findall(r'\d+', raw)

    if nums:
        predicted = max(1, min(150, int(nums[0])))
        errors.append(abs(predicted - true_calls))
        predictions.append(predicted)
        print(f"True: {true_calls:3d}  Predicted: {predicted:3d}  Error: {abs(predicted-true_calls):3d}")
    else:
        print(f"True: {true_calls:3d}  PARSE ERROR: '{raw[:40]}'")

if errors:
    print(f"\nMAE: {np.mean(errors):.1f} calls")
    print(f"Within 10 calls: {sum(1 for e in errors if e <= 10)}/{len(errors)}")
    print(f"Within 20 calls: {sum(1 for e in errors if e <= 20)}/{len(errors)}")
    print(f"Predicted range: {min(predictions)}-{max(predictions)}")
    print(f"Predicted mean: {np.mean(predictions):.1f} (true mean: {np.mean([p['chosen_llm_calls'] for p,_ in labeled[:50]]):.1f})")

True:  73  Predicted:   1  Error:  72
True:  63  Predicted:   1  Error:  62
True:  48  Predicted:   1  Error:  47
True:  68  Predicted:   1  Error:  67
True:  97  Predicted:   1  Error:  96
True:  69  Predicted:   1  Error:  68
True:  87  Predicted:   1  Error:  86
True:  41  Predicted:   1  Error:  40
True:  68  Predicted:   1  Error:  67
True:  41  Predicted:   1  Error:  40
True:  48  Predicted:   1  Error:  47
True:  36  Predicted:   1  Error:  35
True:  66  Predicted:   1  Error:  65
True:  81  Predicted:   1  Error:  80
True:  34  Predicted:   1  Error:  33
True:  74  Predicted:   1  Error:  73
True:  64  Predicted:   1  Error:  63
True:  61  Predicted:   1  Error:  60
True:  48  Predicted:   1  Error:  47
True:  45  Predicted:   1  Error:  44
True:  45  Predicted:   1  Error:  44
True:  45  Predicted:   1  Error:  44
True:  49  Predicted:   1  Error:  48
True:  86  Predicted:   1  Error:  85
True:  43  Predicted:   1  Error:  42
True:  47  Predicted:   1  Error:  46
True:  40  Predicted:   1  Error:  39
True:  88  Predicted:   1  Error:  87
True:  73  Predicted:   1  Error:  72
True:  70  Predicted:   1  Error:  69
True:  70  Predicted:   1  Error:  69
True:  38  Predicted:   1  Error:  37
True:  71  Predicted:   1  Error:  70
True:  40  Predicted:   1  Error:  39
True:  32  Predicted:   1  Error:  31
True:  48  Predicted:   1  Error:  47
True:  41  Predicted:   1  Error:  40
True:  41  Predicted:   1  Error:  40
True:  36  Predicted:   1  Error:  35
True:  77  Predicted:   1  Error:  76
True:  33  Predicted:   1  Error:  32
True:  63  Predicted:   1  Error:  62
True:  42  Predicted:   1  Error:  41
True:  99  Predicted:   1  Error:  98
True:  48  Predicted:   1  Error:  47
True:  78  Predicted:   1  Error:  77
True:  61  Predicted:   1  Error:  60
True:  63  Predicted:   1  Error:  62
True:  41  Predicted:   1  Error:  40
True:  83  Predicted:   1  Error:  82

MAE: 57.1 calls
Within 10 calls: 0/50
Within 20 calls: 0/50
Predicted range: 1-1
Predicted mean: 1.0 (true mean: 58.1)

In [58]:
# Extract embeddings from the current model, train a sklearn regressor on top
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
import numpy as np
import torch

FastLanguageModel.for_inference(model)

def get_embedding(text, max_len=256):
    inputs = tokenizer.tokenizer(
        text, return_tensors="pt", truncation=True,
        max_length=max_len, padding=False
    ).to("cuda")
    with torch.no_grad():
        outputs = model.model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            output_hidden_states=True,
        )
    # Mean pool last hidden state
    hidden = outputs.hidden_states[-1]  # (1, seq_len, hidden_dim)
    mask = inputs["attention_mask"].unsqueeze(-1).float()
    embedding = (hidden * mask).sum(1) / mask.sum(1)
    return embedding.squeeze().cpu().float().numpy()

# Build embedding dataset
print("Extracting embeddings...")
X, y = [], []
for p in raw_pairs:
    if is_successful_trajectory(extract_last_assistant_turn(p["chosen"])):
        emb = get_embedding(p["prompt"][:400])
        X.append(emb)
        y.append(p["chosen_llm_calls"])

X, y = np.array(X), np.array(y)
print(f"Dataset: {X.shape}, y range: {y.min()}-{y.max()}")

# Train ridge regression
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
ridge = Ridge(alpha=1.0)
scores = cross_val_score(ridge, X_scaled, y, cv=5, scoring="neg_mean_absolute_error")
print(f"5-fold CV MAE: {-scores.mean():.1f} ± {scores.std():.1f} calls")

Extracting embeddings...
Dataset: (929, 2560), y range: 26-100
5-fold CV MAE: 15.8 ± 0.6 calls

In [59]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
import pickle

# Fit on full dataset
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
ridge = Ridge(alpha=1.0)
ridge.fit(X_scaled, y)

# Threshold: bottom tercile = HANDLE_LOCALLY
THRESHOLD = int(np.percentile(y, 33))  # ~49 calls
print(f"Routing threshold: {THRESHOLD} calls")

# Eval on held-out
correct = 0
results = []
for pair, expected in labeled:
    emb = get_embedding(pair["prompt"][:400])
    predicted_calls = ridge.predict(scaler.transform([emb]))[0]
    decision = "EFFICIENT" if predicted_calls <= THRESHOLD else "EXPENSIVE"
    correct += (decision == expected)
    results.append({"expected": expected, "predicted": decision,
                    "predicted_calls": predicted_calls,
                    "true_calls": pair["chosen_llm_calls"]})

efficient_cases = [r for r in results if r["expected"] == "EFFICIENT"]
expensive_cases = [r for r in results if r["expected"] == "EXPENSIVE"]

print(f"\nHeld-out accuracy:  {correct}/{len(results)} ({100*correct/len(results):.0f}%)")
print(f"EFFICIENT recall:   {sum(r['predicted']==r['expected'] for r in efficient_cases)}/{len(efficient_cases)}")
print(f"EXPENSIVE recall:   {sum(r['predicted']==r['expected'] for r in expensive_cases)}/{len(expensive_cases)}")

# Save the router
with open("outputs/router_head.pkl", "wb") as f:
    pickle.dump({"scaler": scaler, "ridge": ridge, "threshold": THRESHOLD}, f)
print("\nRouter saved to outputs/router_head.pkl")

Routing threshold: 49 calls

Held-out accuracy:  91/92 (99%)
EFFICIENT recall:   37/38
EXPENSIVE recall:   54/54

Router saved to outputs/router_head.pkl

In [60]:
# Check 1 — is the ridge just learning prompt length?
prompt_lengths = [len(pair["prompt"]) for pair, _ in labeled]
from scipy.stats import pearsonr
true_calls = [pair["chosen_llm_calls"] for pair, _ in labeled]
r, p = pearsonr(prompt_lengths, true_calls)
print(f"Prompt length vs LLM calls correlation: r={r:.3f}, p={p:.4f}")

# Check 2 — does a length-only baseline match the 99%?
length_predictions = [49 + (l - np.mean(prompt_lengths)) * 0.01 for l in prompt_lengths]
length_decisions = ["EFFICIENT" if p <= 49 else "EXPENSIVE" for p in length_predictions]
length_correct = sum(d == expected for (_, expected), d in zip(labeled, length_decisions))
print(f"Length-only baseline accuracy: {length_correct}/{len(labeled)} ({100*length_correct/len(labeled):.0f}%)")

# Check 3 — what's the single misclassified instance?
wrong = [(pair, expected, r) for (pair, expected), r in zip(labeled, results) if r["predicted"] != expected]
for pair, expected, r in wrong:
    print(f"\nMisclassified: true_calls={r['true_calls']}, predicted_calls={r['predicted_calls']:.1f}")
    print(f"Expected: {expected}, Got: {r['predicted']}")
    print(f"Prompt: {pair['prompt'][200:400]}")

Prompt length vs LLM calls correlation: r=0.210, p=0.0449
Length-only baseline accuracy: 46/92 (50%)

Misclassified: true_calls=49, predicted_calls=49.1
Expected: EFFICIENT, Got: EXPENSIVE
Prompt: er the following issue description:

<issue_description>
Make SSL connections the default
In 2017 there is little reasons to connect to a mailbox over plain text.

As this is a breaking change I pro

In [61]:
model.push_to_hub("vedevpatel/escalate-router-regression-v1")
tokenizer.tokenizer.push_to_hub("vedevpatel/escalate-router-regression-v1")

README.md:   0%|          | 0.00/572 [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:  22%|##2       | 6.23MB / 28.1MB

Saved model to https://huggingface.co/vedevpatel/escalate-router-regression-v1

Unsloth: Restored added_tokens_decoder metadata in /tmp/tmpxs3yxa97/tokenizer_config.json.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpxs3yxa97/tokenizer.json: 100%|##########| 32.2MB / 32.2MB